### ISSUE TITLE
fcli ssc appversion update -d desc -n name --session sessionName APP:version -> NPE error // MAC

### ISSUE THREAD

**Issue by xakrurychle** [fortify-ps/fcli#175]
fcli ssc appversion update -d superdesc -n superNAME --session krystof_session FCLIAPP:APPONE
or
qaprague@Jacks-Mac-mini ~ % fcli ssc appversion update -d superdesc -n superNAME --session krystof_session 9

java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:221)
	at java.util.Arrays$ArrayList.<init>(Arrays.java:4323)
	at java.util.Arrays.asList(Arrays.java:4310)
	at com.fortify.cli.ssc.appversion_user.helper.SSCAppVersionAuthEntitiesUpdateBuilder.remove(SSCAppVersionAuthEntitiesUpdateBuilder.java:108)
	at com.fortify.cli.ssc.appversion.cli.cmd.SSCAppVersionUpdateCommand.getUserUpdateRequest(SSCAppVersionUpdateCommand.java:95)
	at com.fortify.cli.ssc.appversion.cli.cmd.SSCAppVersionUpdateCommand.getJsonNode(SSCAppVersionUpdateCommand.java:76)
	at com.fortify.cli.common.output.cli.cmd.unirest.AbstractUnirestOutputCommand.run(AbstractUnirestOutputCommand.java:54)
	at com.fortify.cli.common.rest.cli.mixin.AbstractUnirestRunnerMixin.run(AbstractUnirestRunnerMixin.java:27)
	at com.fortify.cli.common.rest.cli.mixin.AbstractSimpleUnirestRunnerMixin.run(AbstractSimpleUnirestRunnerMixin.java:14)
	at com.fortify.cli.common.rest.cli.cmd.AbstractUnirestRunnerCommand.run(AbstractUnirestRunnerCommand.java:41)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.fortify.cli.app.FortifyCLI.execute(FortifyCLI.java:81)
	at com.fortify.cli.app.FortifyCLI.main(FortifyCLI.java:61)

**Comment by xakrurychle** [comment]
fixed in v1.0.1
