### ISSUE TITLE
fcli ssc attribute-definition get CATEGORY:] _ ATTR_  error, works with id // MAC

### ISSUE THREAD

**Issue by xakrurychle** [fortify-ps/fcli#186]
qaprague@Jacks-Mac-mini ~ % fcli ssc attribute-definition get --session krystof_session TECHNICAL:DevPhase
java.lang.IllegalArgumentException: Attribute id, guid or name 'TECHNICAL:DevPhase' does not exist
	at com.fortify.cli.ssc.attribute_definition.helper.SSCAttributeDefinitionHelper.getAttributeDefinitionDescriptor(SSCAttributeDefinitionHelper.java:90)
	at com.fortify.cli.ssc.attribute_definition.cli.mixin.SSCAttributeDefinitionResolverMixin$AbstractSSCAttributeDefinitionResolverMixin.getAttributeDefinitionDescriptor(SSCAttributeDefinitionResolverMixin.java:41)
	at com.fortify.cli.ssc.attribute_definition.cli.cmd.SSCAttributeDefinitionGetCommand.getJsonNode(SSCAttributeDefinitionGetCommand.java:47)
	at com.fortify.cli.common.output.cli.cmd.unirest.AbstractUnirestOutputCommand.run(AbstractUnirestOutputCommand.java:54)
	at com.fortify.cli.common.rest.cli.mixin.AbstractUnirestRunnerMixin.run(AbstractUnirestRunnerMixin.java:27)
	at com.fortify.cli.common.rest.cli.mixin.AbstractSimpleUnirestRunnerMixin.run(AbstractSimpleUnirestRunnerMixin.java:14)
	at com.fortify.cli.common.rest.cli.cmd.AbstractUnirestRunnerCommand.run(AbstractUnirestRunnerCommand.java:41)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.fortify.cli.app.FortifyCLI.execute(FortifyCLI.java:81)
	at com.fortify.cli.app.FortifyCLI.main(FortifyCLI.java:61)

WORKS WITH ID, eg
fcli ssc attribute-definition get --session krystof_session 5

**Comment by xakrurychle** [comment]
fixed in v1.0.1
