### ISSUE TITLE
fcli ssc plugin enable error // MAC

### ISSUE THREAD

**Issue by xakrurychle** [fortify-ps/fcli#188]
qaprague@Jacks-Mac-mini ~ % fcli ssc plugin enable --session krystof_session 3
kong.unirest.UnirestException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.fortify.cli.ssc.plugin.helper.SSCPluginStateHelper$PluginIdsData and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at kong.unirest.jackson.JacksonObjectMapper.writeValue(JacksonObjectMapper.java:97)
	at kong.unirest.HttpRequestUniBody.body(HttpRequestUniBody.java:70)
	at kong.unirest.HttpRequestBody.body(HttpRequestBody.java:114)
	at com.fortify.cli.ssc.plugin.helper.SSCPluginStateHelper.postPluginId(SSCPluginStateHelper.java:21)
	at com.fortify.cli.ssc.plugin.helper.SSCPluginStateHelper.enablePlugin(SSCPluginStateHelper.java:12)
	at com.fortify.cli.ssc.plugin.cli.cmd.SSCPluginEnableCommand.getJsonNode(SSCPluginEnableCommand.java:50)
	at com.fortify.cli.common.output.cli.cmd.unirest.AbstractUnirestOutputCommand.run(AbstractUnirestOutputCommand.java:54)
	at com.fortify.cli.common.rest.cli.mixin.AbstractUnirestRunnerMixin.run(AbstractUnirestRunnerMixin.java:27)
	at com.fortify.cli.common.rest.cli.mixin.AbstractSimpleUnirestRunnerMixin.run(AbstractSimpleUnirestRunnerMixin.java:14)
	at com.fortify.cli.common.rest.cli.cmd.AbstractUnirestRunnerCommand.run(AbstractUnirestRunnerCommand.java:41)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at com.fortify.cli.app.FortifyCLI.execute(FortifyCLI.java:81)
	at com.fortify.cli.app.FortifyCLI.main(FortifyCLI.java:61)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.fortify.cli.ssc.plugin.helper.SSCPluginStateHelper$PluginIdsData and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:46)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:29)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3821)
	at kong.unirest.jackson.JacksonObjectMapper.writeValue(JacksonObjectMapper.java:95)
	... 18 more

**Comment by rsenden** [comment]
Can you try the same command with the Java version of fcli? Most likely this error is due to a missing annotation that is required for the native binaries; see https://fortify-ps.github.io/fcli/#troubleshooting.
